06-08-2025 21:18:57 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
06-08-2025 21:18:57 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
06-08-2025 21:18:57 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
06-08-2025 21:18:57 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 09:03:02 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
07-08-2025 09:03:02 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
07-08-2025 09:03:02 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
07-08-2025 09:03:02 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 09:34:29 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
07-08-2025 09:34:29 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
07-08-2025 09:34:29 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
07-08-2025 09:34:29 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 09:40:49 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
07-08-2025 09:40:49 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
07-08-2025 09:40:49 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
07-08-2025 09:40:49 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 09:45:02 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
07-08-2025 09:45:02 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
07-08-2025 09:45:02 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
07-08-2025 09:45:02 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 10:13:54 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
07-08-2025 10:13:54 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
07-08-2025 10:13:54 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
07-08-2025 10:13:54 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 10:20:57 - INFO - root - [configurar_logging] - Logging configurado. Os logs serão salvos em: logs\log_bot.log
07-08-2025 10:20:57 - INFO - app.main - [lifespan] - Iniciando a API e configurando recursos...
07-08-2025 10:20:57 - INFO - app.main - [lifespan] - Conectando ao LLM: llama3.1 em http://localhost:11434
07-08-2025 10:20:57 - INFO - app.main - [lifespan] - Instância do LLM criada e pronta para uso.
07-08-2025 10:21:41 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 1/3
07-08-2025 10:21:41 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:21:45 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 1 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509DD1ED0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:21:47 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 2/3
07-08-2025 10:21:47 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:21:51 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 2 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509DD3C10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:21:54 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 1/3
07-08-2025 10:21:54 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:21:58 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 1 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2CF70>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:21:58 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 3/3
07-08-2025 10:21:58 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:22:02 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 3 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2D7B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:02 - ERROR - app.core.cliente_waha - [verificar_sessao] - Erro ao verificar sessão: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2D7B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:02 - ERROR - app.main - [status_whatsapp] - Erro ao verificar status do WhatsApp: 'ClienteWaha' object has no attribute 'session_name'
07-08-2025 10:22:02 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 2/3
07-08-2025 10:22:02 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:22:06 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 2 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509DD3CA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:07 - DEBUG - app.core.cliente_waha - [verificar_sessao] - Usando cache para status da sessão
07-08-2025 10:22:07 - ERROR - app.main - [status_whatsapp] - Erro ao verificar status do WhatsApp: 'ClienteWaha' object has no attribute 'session_name'
07-08-2025 10:22:10 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 3/3
07-08-2025 10:22:10 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:22:14 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 3 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509DD1FC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:14 - ERROR - app.core.cliente_waha - [verificar_sessao] - Erro ao verificar sessão: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509DD1FC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:14 - ERROR - app.main - [status_whatsapp] - Erro ao verificar status do WhatsApp: 'ClienteWaha' object has no attribute 'session_name'
07-08-2025 10:22:18 - DEBUG - app.core.cliente_waha - [verificar_sessao] - Usando cache para status da sessão
07-08-2025 10:22:18 - ERROR - app.main - [status_whatsapp] - Erro ao verificar status do WhatsApp: 'ClienteWaha' object has no attribute 'session_name'
07-08-2025 10:22:27 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 1/3
07-08-2025 10:22:27 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:22:31 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 1 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2E050>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:33 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 2/3
07-08-2025 10:22:33 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:22:38 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 2 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2CB80>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:42 - DEBUG - app.core.cliente_waha - [_fazer_request_com_retry] - Request GET http://localhost:3000/api/sessions/default - Tentativa 3/3
07-08-2025 10:22:42 - DEBUG - urllib3.connectionpool - [_new_conn] - Starting new HTTP connection (1): localhost:3000
07-08-2025 10:22:46 - WARNING - app.core.cliente_waha - [_fazer_request_com_retry] - Tentativa 3 falhou: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2E800>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:46 - ERROR - app.core.cliente_waha - [verificar_sessao] - Erro ao verificar sessão: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/sessions/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B509E2E800>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
07-08-2025 10:22:46 - ERROR - app.main - [status_whatsapp] - Erro ao verificar status do WhatsApp: 'ClienteWaha' object has no attribute 'session_name'
